# GPU sample application
version: "3.9"
services:
  ollama:
    image: ghcr.io/litmusautomation/litmus-ollama-llama3:latest
    container_name: llama3-gpu
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama:
