name: Build and Push Ollama Images

on:
  push:
    branches:
      - main
      - mod_ci
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - ImageName: litmus-ollama-deepseek
            Ollama: 0.10.0
            Models: deepseek-r1:1.5b
          - ImageName: litmus-ollama-llama3
            Ollama: 0.10.0
            Models: llama3.2:1b
          - ImageName: litmus-ollama-qwen3
            Ollama: 0.10.0
            Models: qwen3:8b qwen2.5-coder:0.5b
          - ImageName: litmus-ollama-phi3
            Ollama: 0.10.0
            Models: phi3:3.8b
          - ImageName: litmus-ollama-phi4
            Ollama: 0.10.0
            Models: phi4-mini:3.8b
          - ImageName: litmus-ollama-gemma2
            Ollama: 0.10.0
            Models: gemma2:2b
          - ImageName: litmus-ollama-gemma3
            Ollama: 0.10.0
            Models: gemma3:4b
          - ImageName: litmus-ollama-gemma3n
            Ollama: 0.10.0
            Models: gemma3n:e4b
          - ImageName: litmus-ollama-mistral-nemo
            Ollama: 0.10.0
            Models: mistral-nemo:12b
          # - ImageName: litmus-ollama-mistral3
          #   Ollama: 0.9.3
          #   Models: mistral-small3.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug MODELS value before build
        run: echo "MODELS=${{ matrix.Models }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Ollama images
        uses: docker/build-push-action@v6
        with:
          build-args: |
            OLLAMA_VERSION=${{ matrix.Ollama }}
            MODELS=${{ matrix.Models }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.ImageName }}:latest
